export const tenders = [
  {
    "number": "T12345",
    "name_of_purchase": "Офисные принадлежности",
    "procuring_organization": "ABC Corporation",
    "procurement_format": "Онлайн тендер",
    "procurement_method": "Конкурентное предложение",
    "planned_amount": "25000",
    "publish_date": "2023-11-04",
    "deadline_for_submission": "2023-11-20",
    "validity_period_for_supplier_offers": "2023-12-05",
    "suppliers_offer_guarantee": "1500",
    "official_information": "Пожалуйста, обратитесь к прикрепленным документам",
    "instructions_for_preparing": "Следуйте инструкциям в документе RFP",
    "name_of_company": "XYZ Поставщики Inc.",
    "actual_address": "123 Главная улица, Городок, Область",
    "work_phone": "123-456-7890",
    "remaining_until_purchase": "20 дней",
    "complaints_quantity": 2
  },
  {
    "number": "T54321",
    "name_of_purchase": "Строительные материалы",
    "procuring_organization": "Департамент городских работ города",
    "procurement_format": "Публичный тендер",
    "procurement_method": "Открытый конкурс",
    "planned_amount": "75000",
    "publish_date": "2023-11-06",
    "deadline_for_submission": "2023-11-25",
    "validity_period_for_supplier_offers": "2023-12-10",
    "suppliers_offer_guarantee": "3000",
    "official_information": "Обратитесь к спецификациям и чертежам",
    "instructions_for_preparing": "Следуйте рекомендациям по подаче предложения",
    "name_of_company": "ABC Строй Ltd.",
    "actual_address": "456 Дубовая улица, Городок, Область",
    "work_phone": "987-654-3210",
    "remaining_until_purchase": "19 дней",
    "complaints_quantity": 1
  },
  {
    "number": "T98765",
    "name_of_purchase": "ИТ-услуги",
    "procuring_organization": "Tech Solutions Inc.",
    "procurement_format": "Запрос предложений",
    "procurement_method": "Селективный конкурс",
    "planned_amount": "45000",
    "publish_date": "2023-11-07",
    "deadline_for_submission": "2023-11-22",
    "validity_period_for_supplier_offers": "2023-12-03",
    "suppliers_offer_guarantee": "2000",
    "official_information": "Обратитесь к документу RFP для получения дополнительных сведений",
    "instructions_for_preparing": "Подготовьте предложение в соответствии с рекомендациями RFP",
    "name_of_company": "Инновационные ИТ-решения",
    "actual_address": "789 Вязовая улица, Техноград, Область",
    "work_phone": "555-123-4567",
    "remaining_until_purchase": "15 дней",
    "complaints_quantity": 0
  },
  {
    "number": "T13579",
    "name_of_purchase": "Медицинское оборудование",
    "procuring_organization": "Городская больница",
    "procurement_format": "Конкурентное согласование",
    "procurement_method": "Прямое согласование",
    "planned_amount": "90000",
    "publish_date": "2023-11-10",
    "deadline_for_submission": "2023-11-30",
    "validity_period_for_supplier_offers": "2023-12-15",
    "suppliers_offer_guarantee": "5000",
    "official_information": "Спецификации медицинского оборудования доступны по запросу",
    "instructions_for_preparing": "Подайте предложение с необходимыми удостоверениями",
    "name_of_company": "MediTech Поставки",
    "actual_address": "321 Больничная улица, Здоровый город, Область",
    "work_phone": "888-999-1234",
    "remaining_until_purchase": "20 дней",
    "complaints_quantity": 3
  },
  {
    "number": "T12345",
    "name_of_purchase": "Офисные принадлежности",
    "procuring_organization": "ABC Corporation",
    "procurement_format": "Онлайн тендер",
    "procurement_method": "Конкурентное предложение",
    "planned_amount": "25000",
    "publish_date": "2023-11-04",
    "deadline_for_submission": "2023-11-20",
    "validity_period_for_supplier_offers": "2023-12-05",
    "suppliers_offer_guarantee": "1500",
    "official_information": "Пожалуйста, обратитесь к прикрепленным документам",
    "instructions_for_preparing": "Следуйте инструкциям в документе RFP",
    "name_of_company": "XYZ Поставщики Inc.",
    "actual_address": "123 Главная улица, Городок, Область",
    "work_phone": "123-456-7890",
    "remaining_until_purchase": "20 дней",
    "complaints_quantity": 2
  },
  {
    "number": "T54321",
    "name_of_purchase": "Строительные материалы",
    "procuring_organization": "Департамент городских работ города",
    "procurement_format": "Публичный тендер",
    "procurement_method": "Открытый конкурс",
    "planned_amount": "75000",
    "publish_date": "2023-11-06",
    "deadline_for_submission": "2023-11-25",
    "validity_period_for_supplier_offers": "2023-12-10",
    "suppliers_offer_guarantee": "3000",
    "official_information": "Обратитесь к спецификациям и чертежам",
    "instructions_for_preparing": "Следуйте рекомендациям по подаче предложения",
    "name_of_company": "ABC Строй Ltd.",
    "actual_address": "456 Дубовая улица, Городок, Область",
    "work_phone": "987-654-3210",
    "remaining_until_purchase": "19 дней",
    "complaints_quantity": 1
  },
  {
    "number": "T98765",
    "name_of_purchase": "ИТ-услуги",
    "procuring_organization": "Tech Solutions Inc.",
    "procurement_format": "Запрос предложений",
    "procurement_method": "Селективный конкурс",
    "planned_amount": "45000",
    "publish_date": "2023-11-07",
    "deadline_for_submission": "2023-11-22",
    "validity_period_for_supplier_offers": "2023-12-03",
    "suppliers_offer_guarantee": "2000",
    "official_information": "Обратитесь к документу RFP для получения дополнительных сведений",
    "instructions_for_preparing": "Подготовьте предложение в соответствии с рекомендациями RFP",
    "name_of_company": "Инновационные ИТ-решения",
    "actual_address": "789 Вязовая улица, Техноград, Область",
    "work_phone": "555-123-4567",
    "remaining_until_purchase": "15 дней",
    "complaints_quantity": 0
  },
  {
    "number": "T13579",
    "name_of_purchase": "Медицинское оборудование",
    "procuring_organization": "Городская больница",
    "procurement_format": "Конкурентное согласование",
    "procurement_method": "Прямое согласование",
    "planned_amount": "90000",
    "publish_date": "2023-11-10",
    "deadline_for_submission": "2023-11-30",
    "validity_period_for_supplier_offers": "2023-12-15",
    "suppliers_offer_guarantee": "5000",
    "official_information": "Спецификации медицинского оборудования доступны по запросу",
    "instructions_for_preparing": "Подайте предложение с необходимыми удостоверениями",
    "name_of_company": "MediTech Поставки",
    "actual_address": "321 Больничная улица, Здоровый город, Область",
    "work_phone": "888-999-1234",
    "remaining_until_purchase": "20 дней",
    "complaints_quantity": 3
  },
  {
    "number": "T12345",
    "name_of_purchase": "Офисные принадлежности",
    "procuring_organization": "ABC Corporation",
    "procurement_format": "Онлайн тендер",
    "procurement_method": "Конкурентное предложение",
    "planned_amount": "25000",
    "publish_date": "2023-11-04",
    "deadline_for_submission": "2023-11-20",
    "validity_period_for_supplier_offers": "2023-12-05",
    "suppliers_offer_guarantee": "1500",
    "official_information": "Пожалуйста, обратитесь к прикрепленным документам",
    "instructions_for_preparing": "Следуйте инструкциям в документе RFP",
    "name_of_company": "XYZ Поставщики Inc.",
    "actual_address": "123 Главная улица, Городок, Область",
    "work_phone": "123-456-7890",
    "remaining_until_purchase": "20 дней",
    "complaints_quantity": 2
  },
  {
    "number": "T54321",
    "name_of_purchase": "Строительные материалы",
    "procuring_organization": "Департамент городских работ города",
    "procurement_format": "Публичный тендер",
    "procurement_method": "Открытый конкурс",
    "planned_amount": "75000",
    "publish_date": "2023-11-06",
    "deadline_for_submission": "2023-11-25",
    "validity_period_for_supplier_offers": "2023-12-10",
    "suppliers_offer_guarantee": "3000",
    "official_information": "Обратитесь к спецификациям и чертежам",
    "instructions_for_preparing": "Следуйте рекомендациям по подаче предложения",
    "name_of_company": "ABC Строй Ltd.",
    "actual_address": "456 Дубовая улица, Городок, Область",
    "work_phone": "987-654-3210",
    "remaining_until_purchase": "19 дней",
    "complaints_quantity": 1
  },
  {
    "number": "T98765",
    "name_of_purchase": "ИТ-услуги",
    "procuring_organization": "Tech Solutions Inc.",
    "procurement_format": "Запрос предложений",
    "procurement_method": "Селективный конкурс",
    "planned_amount": "45000",
    "publish_date": "2023-11-07",
    "deadline_for_submission": "2023-11-22",
    "validity_period_for_supplier_offers": "2023-12-03",
    "suppliers_offer_guarantee": "2000",
    "official_information": "Обратитесь к документу RFP для получения дополнительных сведений",
    "instructions_for_preparing": "Подготовьте предложение в соответствии с рекомендациями RFP",
    "name_of_company": "Инновационные ИТ-решения",
    "actual_address": "789 Вязовая улица, Техноград, Область",
    "work_phone": "555-123-4567",
    "remaining_until_purchase": "15 дней",
    "complaints_quantity": 0
  },
  {
    "number": "T13579",
    "name_of_purchase": "Медицинское оборудование",
    "procuring_organization": "Городская больница",
    "procurement_format": "Конкурентное согласование",
    "procurement_method": "Прямое согласование",
    "planned_amount": "90000",
    "publish_date": "2023-11-10",
    "deadline_for_submission": "2023-11-30",
    "validity_period_for_supplier_offers": "2023-12-15",
    "suppliers_offer_guarantee": "5000",
    "official_information": "Спецификации медицинского оборудования доступны по запросу",
    "instructions_for_preparing": "Подайте предложение с необходимыми удостоверениями",
    "name_of_company": "MediTech Поставки",
    "actual_address": "321 Больничная улица, Здоровый город, Область",
    "work_phone": "888-999-1234",
    "remaining_until_purchase": "20 дней",
    "complaints_quantity": 3
  },
  {
    "number": "T12345",
    "name_of_purchase": "Офисные принадлежности",
    "procuring_organization": "ABC Corporation",
    "procurement_format": "Онлайн тендер",
    "procurement_method": "Конкурентное предложение",
    "planned_amount": "25000",
    "publish_date": "2023-11-04",
    "deadline_for_submission": "2023-11-20",
    "validity_period_for_supplier_offers": "2023-12-05",
    "suppliers_offer_guarantee": "1500",
    "official_information": "Пожалуйста, обратитесь к прикрепленным документам",
    "instructions_for_preparing": "Следуйте инструкциям в документе RFP",
    "name_of_company": "XYZ Поставщики Inc.",
    "actual_address": "123 Главная улица, Городок, Область",
    "work_phone": "123-456-7890",
    "remaining_until_purchase": "20 дней",
    "complaints_quantity": 2
  },
  {
    "number": "T54321",
    "name_of_purchase": "Строительные материалы",
    "procuring_organization": "Департамент городских работ города",
    "procurement_format": "Публичный тендер",
    "procurement_method": "Открытый конкурс",
    "planned_amount": "75000",
    "publish_date": "2023-11-06",
    "deadline_for_submission": "2023-11-25",
    "validity_period_for_supplier_offers": "2023-12-10",
    "suppliers_offer_guarantee": "3000",
    "official_information": "Обратитесь к спецификациям и чертежам",
    "instructions_for_preparing": "Следуйте рекомендациям по подаче предложения",
    "name_of_company": "ABC Строй Ltd.",
    "actual_address": "456 Дубовая улица, Городок, Область",
    "work_phone": "987-654-3210",
    "remaining_until_purchase": "19 дней",
    "complaints_quantity": 1
  },
  {
    "number": "T98765",
    "name_of_purchase": "ИТ-услуги",
    "procuring_organization": "Tech Solutions Inc.",
    "procurement_format": "Запрос предложений",
    "procurement_method": "Селективный конкурс",
    "planned_amount": "45000",
    "publish_date": "2023-11-07",
    "deadline_for_submission": "2023-11-22",
    "validity_period_for_supplier_offers": "2023-12-03",
    "suppliers_offer_guarantee": "2000",
    "official_information": "Обратитесь к документу RFP для получения дополнительных сведений",
    "instructions_for_preparing": "Подготовьте предложение в соответствии с рекомендациями RFP",
    "name_of_company": "Инновационные ИТ-решения",
    "actual_address": "789 Вязовая улица, Техноград, Область",
    "work_phone": "555-123-4567",
    "remaining_until_purchase": "15 дней",
    "complaints_quantity": 0
  },
  {
    "number": "T13579",
    "name_of_purchase": "Медицинское оборудование",
    "procuring_organization": "Городская больница",
    "procurement_format": "Конкурентное согласование",
    "procurement_method": "Прямое согласование",
    "planned_amount": "90000",
    "publish_date": "2023-11-10",
    "deadline_for_submission": "2023-11-30",
    "validity_period_for_supplier_offers": "2023-12-15",
    "suppliers_offer_guarantee": "5000",
    "official_information": "Спецификации медицинского оборудования доступны по запросу",
    "instructions_for_preparing": "Подайте предложение с необходимыми удостоверениями",
    "name_of_company": "MediTech Поставки",
    "actual_address": "321 Больничная улица, Здоровый город, Область",
    "work_phone": "888-999-1234",
    "remaining_until_purchase": "20 дней",
    "complaints_quantity": 3
  },
  {
    "number": "T12345",
    "name_of_purchase": "Офисные принадлежности",
    "procuring_organization": "ABC Corporation",
    "procurement_format": "Онлайн тендер",
    "procurement_method": "Конкурентное предложение",
    "planned_amount": "25000",
    "publish_date": "2023-11-04",
    "deadline_for_submission": "2023-11-20",
    "validity_period_for_supplier_offers": "2023-12-05",
    "suppliers_offer_guarantee": "1500",
    "official_information": "Пожалуйста, обратитесь к прикрепленным документам",
    "instructions_for_preparing": "Следуйте инструкциям в документе RFP",
    "name_of_company": "XYZ Поставщики Inc.",
    "actual_address": "123 Главная улица, Городок, Область",
    "work_phone": "123-456-7890",
    "remaining_until_purchase": "20 дней",
    "complaints_quantity": 2
  },
  {
    "number": "T54321",
    "name_of_purchase": "Строительные материалы",
    "procuring_organization": "Департамент городских работ города",
    "procurement_format": "Публичный тендер",
    "procurement_method": "Открытый конкурс",
    "planned_amount": "75000",
    "publish_date": "2023-11-06",
    "deadline_for_submission": "2023-11-25",
    "validity_period_for_supplier_offers": "2023-12-10",
    "suppliers_offer_guarantee": "3000",
    "official_information": "Обратитесь к спецификациям и чертежам",
    "instructions_for_preparing": "Следуйте рекомендациям по подаче предложения",
    "name_of_company": "ABC Строй Ltd.",
    "actual_address": "456 Дубовая улица, Городок, Область",
    "work_phone": "987-654-3210",
    "remaining_until_purchase": "19 дней",
    "complaints_quantity": 1
  },
  {
    "number": "T98765",
    "name_of_purchase": "ИТ-услуги",
    "procuring_organization": "Tech Solutions Inc.",
    "procurement_format": "Запрос предложений",
    "procurement_method": "Селективный конкурс",
    "planned_amount": "45000",
    "publish_date": "2023-11-07",
    "deadline_for_submission": "2023-11-22",
    "validity_period_for_supplier_offers": "2023-12-03",
    "suppliers_offer_guarantee": "2000",
    "official_information": "Обратитесь к документу RFP для получения дополнительных сведений",
    "instructions_for_preparing": "Подготовьте предложение в соответствии с рекомендациями RFP",
    "name_of_company": "Инновационные ИТ-решения",
    "actual_address": "789 Вязовая улица, Техноград, Область",
    "work_phone": "555-123-4567",
    "remaining_until_purchase": "15 дней",
    "complaints_quantity": 0
  },
  {
    "number": "T13579",
    "name_of_purchase": "Медицинское оборудование",
    "procuring_organization": "Городская больница",
    "procurement_format": "Конкурентное согласование",
    "procurement_method": "Прямое согласование",
    "planned_amount": "90000",
    "publish_date": "2023-11-10",
    "deadline_for_submission": "2023-11-30",
    "validity_period_for_supplier_offers": "2023-12-15",
    "suppliers_offer_guarantee": "5000",
    "official_information": "Спецификации медицинского оборудования доступны по запросу",
    "instructions_for_preparing": "Подайте предложение с необходимыми удостоверениями",
    "name_of_company": "MediTech Поставки",
    "actual_address": "321 Больничная улица, Здоровый город, Область",
    "work_phone": "888-999-1234",
    "remaining_until_purchase": "20 дней",
    "complaints_quantity": 3
  }
];
